Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from myst_nb import glue
import yaml
try:
    with open('_config.yml') as f:
        config = next(yaml.load_all(f, Loader=yaml.FullLoader))
except FileNotFoundError:
    print('No config file found')
# let's prime a bunch of variables
glue("replmd", config["other"]["replmd"])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[1], line 9[0m
[1;32m      7[0m     [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mNo config file found[39m[38;5;124m'[39m)
[1;32m      8[0m [38;5;66;03m# let's prime a bunch of variables[39;00m
[0;32m----> 9[0m glue([38;5;124m"[39m[38;5;124mreplmd[39m[38;5;124m"[39m, [43mconfig[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mother[39;49m[38;5;124;43m"[39;49m[43m][49m[[38;5;124m"[39m[38;5;124mreplmd[39m[38;5;124m"[39m])

[0;31mKeyError[0m: 'other'

